---
device:
  0:
    PC_PORT_PHYS_MAP:
      ?
        PORT_ID: 0
      :
        PC_PHYS_PORT_ID: 0
      ?
        PORT_ID: 1
      :
        PC_PHYS_PORT_ID: 1
      ?
        PORT_ID: 2
      :
        PC_PHYS_PORT_ID: 9
      ?
        PORT_ID: 11
      :
        PC_PHYS_PORT_ID: 17
      ?
        PORT_ID: 12
      :
        PC_PHYS_PORT_ID: 25
      ?
        PORT_ID: 22
      :
        PC_PHYS_PORT_ID: 33
      ?
        PORT_ID: 23
      :
        PC_PHYS_PORT_ID: 41
      ?
        PORT_ID: 33
      :
        PC_PHYS_PORT_ID: 49
      ?
        PORT_ID: 34
      :
        PC_PHYS_PORT_ID: 57
      ?
        PORT_ID: 44
      :
        PC_PHYS_PORT_ID: 65
      ?
        PORT_ID: 45
      :
        PC_PHYS_PORT_ID: 73
      ?
        PORT_ID: 55
      :
        PC_PHYS_PORT_ID: 81
      ?
        PORT_ID: 56
      :
        PC_PHYS_PORT_ID: 89
      ?
        PORT_ID: 66
      :
        PC_PHYS_PORT_ID: 97
      ?
        PORT_ID: 67
      :
        PC_PHYS_PORT_ID: 105
      ?
        PORT_ID: 77
      :
        PC_PHYS_PORT_ID: 113
      ?
        PORT_ID: 78
      :
        PC_PHYS_PORT_ID: 121
      ?
        PORT_ID: 88
      :
        PC_PHYS_PORT_ID: 129
      ?
        PORT_ID: 89
      :
        PC_PHYS_PORT_ID: 137
      ?
        PORT_ID: 99
      :
        PC_PHYS_PORT_ID: 145
      ?
        PORT_ID: 100
      :
        PC_PHYS_PORT_ID: 153
      ?
        PORT_ID: 110
      :
        PC_PHYS_PORT_ID: 161
      ?
        PORT_ID: 111
      :
        PC_PHYS_PORT_ID: 169
      ?
        PORT_ID: 121
      :
        PC_PHYS_PORT_ID: 177
      ?
        PORT_ID: 122
      :
        PC_PHYS_PORT_ID: 185
      ?
        PORT_ID: 132
      :
        PC_PHYS_PORT_ID: 193
      ?
        PORT_ID: 133
      :
        PC_PHYS_PORT_ID: 201
      ?
        PORT_ID: 143
      :
        PC_PHYS_PORT_ID: 209
      ?
        PORT_ID: 144
      :
        PC_PHYS_PORT_ID: 217
      ?
        PORT_ID: 154
      :
        PC_PHYS_PORT_ID: 225
      ?
        PORT_ID: 155
      :
        PC_PHYS_PORT_ID: 233
      ?
        PORT_ID: 165
      :
        PC_PHYS_PORT_ID: 241
      ?
        PORT_ID: 166
      :
        PC_PHYS_PORT_ID: 249
      ?
        PORT_ID: 176
      :
        PC_PHYS_PORT_ID: 257
      ?
        PORT_ID: 177
      :
        PC_PHYS_PORT_ID: 265
      ?
        PORT_ID: 187
      :
        PC_PHYS_PORT_ID: 273
      ?
        PORT_ID: 188
      :
        PC_PHYS_PORT_ID: 281
      ?
        PORT_ID: 198
      :
        PC_PHYS_PORT_ID: 289
      ?
        PORT_ID: 199
      :
        PC_PHYS_PORT_ID: 297
      ?
        PORT_ID: 209
      :
        PC_PHYS_PORT_ID: 305
      ?
        PORT_ID: 210
      :
        PC_PHYS_PORT_ID: 313
      ?
        PORT_ID: 220
      :
        PC_PHYS_PORT_ID: 321
      ?
        PORT_ID: 221
      :
        PC_PHYS_PORT_ID: 329
      ?
        PORT_ID: 231
      :
        PC_PHYS_PORT_ID: 337
      ?
        PORT_ID: 232
      :
        PC_PHYS_PORT_ID: 345
      ?
        PORT_ID: 242
      :
        PC_PHYS_PORT_ID: 353
      ?
        PORT_ID: 243
      :
        PC_PHYS_PORT_ID: 361
      ?
        PORT_ID: 253
      :
        PC_PHYS_PORT_ID: 369
      ?
        PORT_ID: 254
      :
        PC_PHYS_PORT_ID: 377
      ?
        PORT_ID: 264
      :
        PC_PHYS_PORT_ID: 385
      ?
        PORT_ID: 265
      :
        PC_PHYS_PORT_ID: 393
      ?
        PORT_ID: 275
      :
        PC_PHYS_PORT_ID: 401
      ?
        PORT_ID: 276
      :
        PC_PHYS_PORT_ID: 409
      ?
        PORT_ID: 286
      :
        PC_PHYS_PORT_ID: 417
      ?
        PORT_ID: 287
      :
        PC_PHYS_PORT_ID: 425
      ?
        PORT_ID: 297
      :
        PC_PHYS_PORT_ID: 433
      ?
        PORT_ID: 298
      :
        PC_PHYS_PORT_ID: 441
      ?
        PORT_ID: 308
      :
        PC_PHYS_PORT_ID: 449
      ?
        PORT_ID: 309
      :
        PC_PHYS_PORT_ID: 457
      ?
        PORT_ID: 319
      :
        PC_PHYS_PORT_ID: 465
      ?
        PORT_ID: 320
      :
        PC_PHYS_PORT_ID: 473
      ?
        PORT_ID: 330
      :
        PC_PHYS_PORT_ID: 481
      ?
        PORT_ID: 331
      :
        PC_PHYS_PORT_ID: 489
      ?
        PORT_ID: 341
      :
        PC_PHYS_PORT_ID: 497
      ?
        PORT_ID: 342
      :
        PC_PHYS_PORT_ID: 505
        #?
        #PORT_ID: 76
        #:
        #PC_PHYS_PORT_ID: 513
        #?
        #PORT_ID: 164
        #:
        #PC_PHYS_PORT_ID: 514
        #?
        #PORT_ID: 274
        #:
        #PC_PHYS_PORT_ID: 515
        #?
        #PORT_ID: 186
        #:
        #PC_PHYS_PORT_ID: 516
...
---
device:
  0:
    PC_PORT:
      ?
        PORT_ID: [[1, 2], [11, 12], [22, 23], [33, 34],
                  [44, 45], [55, 56], [66, 67], [77, 78],
                  [88, 89], [99, 100], [110, 111], [121, 122],
                  [132, 133], [143, 144], [154, 155], [165, 166],
                  [176, 177], [187, 188], [198, 199], [209, 210],
                  [220, 221], [231, 232], [242, 243], [253, 254],
                  [264, 265], [275, 276], [286, 287], [297, 298],
                  [308, 309], [319, 320], [330, 331], [341, 342]]
      :
        ENABLE: 1
        SPEED: 800000
        NUM_LANES: 8
        FEC_MODE: PC_FEC_RS544_2XN
        #LINK_TRAINING: 1
        MAX_FRAME_SIZE: 9416
        #?
        #PORT_ID: [76, 164, 186, 274]
        #:
        #ENABLE: 1
        #SPEED: 25000
        #NUM_LANES: 1
        #FEC_MODE: PC_FEC_NONE
        #MAX_FRAME_SIZE: 9416
      ?
        PORT_ID: 0
      :
        ENABLE: 1
        SPEED: 10000
        NUM_LANES: 1
        FEC_MODE: PC_FEC_NONE

    PC_PMD_FIRMWARE:
      ?
        PORT_ID: [[1, 2], [11, 12], [22, 23], [33, 34],
                  [44, 45], [55, 56], [66, 67], [77, 78],
                  [88, 89], [99, 100], [110, 111], [121, 122],
                  [132, 133], [143, 144], [154, 155], [165, 166],
                  [176, 177], [187, 188], [198, 199], [209, 210],
                  [220, 221], [231, 232], [242, 243], [253, 254],
                  [264, 265], [275, 276], [286, 287], [297, 298],
                  [308, 309], [319, 320], [330, 331], [341, 342]]
      :
        MEDIUM_TYPE_AUTO: 0
        MEDIUM_TYPE: PC_PHY_MEDIUM_BACKPLANE
...
---
device:
    0:
        # Per pipe flex counter configuration
        CTR_EFLEX_CONFIG:
            CTR_ING_EFLEX_OPERMODE_PIPEUNIQUE: 0
            CTR_EGR_EFLEX_OPERMODE_PIPEUNIQUE: 0
...
---
device:
    0:
        FP_CONFIG:
            FP_ING_OPERMODE: GLOBAL_PIPE_AWARE
            FP_VLAN_OPERMODE_PIPEUNIQUE: 0
            FP_EGR_OPERMODE_PIPEUNIQUE: 0
...
---
bcm_device:
    0:
        global:
            pktio_mode: 1
            l2_hitbit_enable: 1
            vlan_flooding_l2mc_num_reserved: 2048
            l2_learn_enable: 1
            max_vp_lags: 8
            vlan_default_port: 3
            l3_ecmp_member_first_lkup_mem_size: 8192
            port_led_link_speed_mode: 5
...
---
# MMU attributes
device:
  0:
# Mapping UC input priorities to PG (0-0,1-1,2-2,3-3,4-4,5-5,6-6,[7-15]-7)
   TM_ING_UC_ING_PRI_MAP:
       ?
       TM_ING_UC_ING_PRI_MAP_ID: 1
       ING_PRI: 0
       :
       TM_PRI_GRP_ID: 0
       ?
       TM_ING_UC_ING_PRI_MAP_ID: 1
       ING_PRI: 1
       :
       TM_PRI_GRP_ID: 1
       ?
       TM_ING_UC_ING_PRI_MAP_ID: 1
       ING_PRI: 2
       :
       TM_PRI_GRP_ID: 2
       ?
       TM_ING_UC_ING_PRI_MAP_ID: 1
       ING_PRI: 3
       :
       TM_PRI_GRP_ID: 3
       ?
       TM_ING_UC_ING_PRI_MAP_ID: 1
       ING_PRI: 4
       :
       TM_PRI_GRP_ID: 4
       ?
       TM_ING_UC_ING_PRI_MAP_ID: 1
       ING_PRI: 5
       :
       TM_PRI_GRP_ID: 5
       ?
       TM_ING_UC_ING_PRI_MAP_ID: 1
       ING_PRI: 6
       :
       TM_PRI_GRP_ID: 6
       ?
       TM_ING_UC_ING_PRI_MAP_ID: 1
       ING_PRI: [[7,15]]
       :
       TM_PRI_GRP_ID: 7
# Mapping UC input priorities to PG ([0-7]-0,8-1,9-2,10-3,11-4,12-5,13-6, [14-15]-7)
       ?
       TM_ING_UC_ING_PRI_MAP_ID: 2
       ING_PRI: [[0,7]]
       :
       TM_PRI_GRP_ID: 0
       ?
       TM_ING_UC_ING_PRI_MAP_ID: 2
       ING_PRI: 8
       :
       TM_PRI_GRP_ID: 1
       ?
       TM_ING_UC_ING_PRI_MAP_ID: 2
       ING_PRI: 9
       :
       TM_PRI_GRP_ID: 2
       ?
       TM_ING_UC_ING_PRI_MAP_ID: 2
       ING_PRI: 10
       :
       TM_PRI_GRP_ID: 3
       ?
       TM_ING_UC_ING_PRI_MAP_ID: 2
       ING_PRI: 11
       :
       TM_PRI_GRP_ID: 4
       ?
       TM_ING_UC_ING_PRI_MAP_ID: 2
       ING_PRI: 12
       :
       TM_PRI_GRP_ID: 5
       ?
       TM_ING_UC_ING_PRI_MAP_ID: 2
       ING_PRI: 13
       :
       TM_PRI_GRP_ID: 6
       ?
       TM_ING_UC_ING_PRI_MAP_ID: 2
       ING_PRI: [[14,15]]
       :
       TM_PRI_GRP_ID: 7
 # Mapping PG to SP (0-0,1-0,2-0,3-0,4-1,5-1,6-1,7-1)
 # Mapping PG to HP (0-0,1-0,2-0,3-0,4-1,5-1,6-1,7-1)
   TM_PRI_GRP_POOL_MAP:
       ?
       TM_PRI_GRP_POOL_MAP_ID: 1
       TM_PRI_GRP_ID: 0
       :
       TM_ING_SERVICE_POOL_ID: 0
       TM_HEADROOM_POOL_ID: 0
       ?
       TM_PRI_GRP_POOL_MAP_ID: 1
       TM_PRI_GRP_ID: 1
       :
       TM_ING_SERVICE_POOL_ID: 0
       TM_HEADROOM_POOL_ID: 0
       ?
       TM_PRI_GRP_POOL_MAP_ID: 1
       TM_PRI_GRP_ID: 2
       :
       TM_ING_SERVICE_POOL_ID: 0
       TM_HEADROOM_POOL_ID: 0
       ?
       TM_PRI_GRP_POOL_MAP_ID: 1
       TM_PRI_GRP_ID: 3
       :
       TM_ING_SERVICE_POOL_ID: 0
       TM_HEADROOM_POOL_ID: 0
       ?
       TM_PRI_GRP_POOL_MAP_ID: 1
       TM_PRI_GRP_ID: 4
       :
       TM_ING_SERVICE_POOL_ID: 1
       TM_HEADROOM_POOL_ID: 1
       ?
       TM_PRI_GRP_POOL_MAP_ID: 1
       TM_PRI_GRP_ID: 5
       :
       TM_ING_SERVICE_POOL_ID: 1
       TM_HEADROOM_POOL_ID: 1
       ?
       TM_PRI_GRP_POOL_MAP_ID: 1
       TM_PRI_GRP_ID: 6
       :
       TM_ING_SERVICE_POOL_ID: 1
       TM_HEADROOM_POOL_ID: 1
       ?
       TM_PRI_GRP_POOL_MAP_ID: 1
       TM_PRI_GRP_ID: 7
       :
       TM_ING_SERVICE_POOL_ID: 1
       TM_HEADROOM_POOL_ID: 1
 # Mapping PG to SP (0-0,1-1,2-2,3-3,4-3,5-3,6-3,7-3)
 # Mapping PG to HP (0-0,1-1,2-2,3-3,4-3,5-3,6-3,7-3)
       ?
       TM_PRI_GRP_POOL_MAP_ID: 2
       TM_PRI_GRP_ID: 0
       :
       TM_ING_SERVICE_POOL_ID: 0
       TM_HEADROOM_POOL_ID: 0
       ?
       TM_PRI_GRP_POOL_MAP_ID: 2
       TM_PRI_GRP_ID: 1
       :
       TM_ING_SERVICE_POOL_ID: 1
       TM_HEADROOM_POOL_ID: 1
       ?
       TM_PRI_GRP_POOL_MAP_ID: 2
       TM_PRI_GRP_ID: 2
       :
       TM_ING_SERVICE_POOL_ID: 2
       TM_HEADROOM_POOL_ID: 2
       ?
       TM_PRI_GRP_POOL_MAP_ID: 2
       TM_PRI_GRP_ID: 3
       :
       TM_ING_SERVICE_POOL_ID: 3
       TM_HEADROOM_POOL_ID: 3
       ?
       TM_PRI_GRP_POOL_MAP_ID: 2
       TM_PRI_GRP_ID: 4
       :
       TM_ING_SERVICE_POOL_ID: 3
       TM_HEADROOM_POOL_ID: 3
       ?
       TM_PRI_GRP_POOL_MAP_ID: 2
       TM_PRI_GRP_ID: 5
       :
       TM_ING_SERVICE_POOL_ID: 3
       TM_HEADROOM_POOL_ID: 3
       ?
       TM_PRI_GRP_POOL_MAP_ID: 2
       TM_PRI_GRP_ID: 6
       :
       TM_ING_SERVICE_POOL_ID: 3
       TM_HEADROOM_POOL_ID: 3
       ?
       TM_PRI_GRP_POOL_MAP_ID: 2
       TM_PRI_GRP_ID: 7
       :
       TM_ING_SERVICE_POOL_ID: 3
       TM_HEADROOM_POOL_ID: 3
# Attaching ING_PRI_PG-1 and ING_PG_SP-1 to port 1
   TM_ING_PORT:
       ?
       PORT_ID:1
       :
       ING_PRI_MAP_ID:1
       PRI_GRP_MAP_ID:1
       ?
       PORT_ID:2
       :
       ING_PRI_MAP_ID:1
       PRI_GRP_MAP_ID:1
# Per port PG threshold configurations.
   TM_ING_THD_PORT_PRI_GRP:
       ?
       PORT_ID: 1
      # lossy PG
       TM_PRI_GRP_ID: [[0, 3]]
       :
       MIN_GUARANTEE_CELLS: 7
       DYNAMIC_SHARED_LIMITS: 1
       SHARED_LIMIT_DYNAMIC: ALPHA_1_128
       HEADROOM_LIMIT_CELLS: 0
       ?
       PORT_ID: 1
      # Lossless PGâ€™s
       TM_PRI_GRP_ID: [[4, 7]]
       :
       MIN_GUARANTEE_CELLS: 335
       DYNAMIC_SHARED_LIMITS: 0
       SHARED_LIMIT_CELLS_STATIC: 1350
       HEADROOM_LIMIT_CELLS: 1889
...
